### ISSUE TITLE
can't set cookieManager.setAcceptFileSchemeCookies

### ISSUE THREAD

**Issue by vagusX** [zsxsoft/cordova-plugin-x5-tbs#1]
```
    //REALLY? Nobody has seen this UNTIL NOW?
    // cookieManager.setAcceptFileSchemeCookies(true);
```

**Comment by zsxsoft** [comment]
That's because X5 SDK doesn't have this method, and I found no way to implement it.

You can see ``setAcceptFileSchemeCookies`` in Crosswalk, it calls ``nativeSetAcceptFileSchemeCookies``. (https://github.com/crosswalk-project/crosswalk/blob/e3259b966dcedd18dc456b8cc97cd1a52aad58ea/runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java)
